### ISSUE TITLE
Not working on Anki 23.10.1

### ISSUE THREAD

**Issue by toxyy** [axelmoreen/AnkiBuddy#10]
![image](https://github.com/axelmoreen/AnkiBuddy/assets/29783193/eaba9fdf-6968-43aa-9584-d2f15618dd40)

```Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22000
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-11-19 11:52:32
When loading AnkiBuddy - Custom Practice:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\myaccount\AppData\Roaming\Anki2\addons21\1704476211\__init__.py", line 6, in <module>
    from .hooks import patch_all
  File "C:\Users\myaccount\AppData\Roaming\Anki2\addons21\1704476211\hooks.py", line 15, in <module>
    from .dialogs import QuestionsDialog
  File "C:\Users\myaccount\AppData\Roaming\Anki2\addons21\1704476211\dialogs\__init__.py", line 7, in <module>
    from .options_dialog import OptionsDialog
  File "C:\Users\myaccount\AppData\Roaming\Anki2\addons21\1704476211\dialogs\options_dialog.py", line 11, in <module>
    from ..forms.options import Ui_OptionsDialog
  File "C:\Users\myaccount\AppData\Roaming\Anki2\addons21\1704476211\forms\options.py", line 11, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'```

**Comment by toxyy** [comment]
Fixed the issues with my PR here:
https://github.com/axelmoreen/AnkiBuddy/pull/11

I can now finally use this addon again.
