### ISSUE TITLE
Caught Exception when using with Hangul deck? 

### ISSUE THREAD

**Issue by niccup1992** [axelmoreen/AnkiBuddy#9]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-25 15:48:40
Add-ons possibly involved: ⁨AnkiBuddy - Custom Practice⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 659, in _onBridgeCmd
  File "_aqt.hooks", line 5351, in __call__
  File "C:\Users\nicol\AppData\Roaming\Anki2\addons21\1704476211\hooks.py", line 51, in _receive_pycmd
    nstore = notecards.get(curr_did)
  File "C:\Users\nicol\AppData\Roaming\Anki2\addons21\1704476211\const.py", line 57, in get
    store.sort(options.get_globals(store.deck_name)["sort"])
  File "C:\Users\nicol\AppData\Roaming\Anki2\addons21\1704476211\stores.py", line 96, in sort
    self.notecards.sort(key=lambda note: int(note.fields[index]),
  File "C:\Users\nicol\AppData\Roaming\Anki2\addons21\1704476211\stores.py", line 96, in <lambda>
    self.notecards.sort(key=lambda note: int(note.fields[index]),
ValueError: invalid literal for int() with base 10: 'ㄱ'

**Comment by niccup1992** [comment]
After researching for a bit, the problem is "ValueError: invalid literal for int() with base 10: 'ㄱ'". 

I haven't found the solution, but I imagine a solution similar to getting Furigana to work with Ankibuddy would work here too. Python won't read Hangul as a integer with base 10.
